<?php
/**
 * @file The main plugin for iMoneza
 * 
 * @author Aaron Saray
 */

/** load in my own composer stuff for this moment */
require_once 'vendor/autoload.php';

/**
 * Implements hook_menu()
 *
 * This generates an iMoneza menu item at the main level.
 *
 * @return array
 */
function imoneza_menu() {
  $iMoneza = \iMoneza\Drupal\App::getInstance();
  return $iMoneza->menu();
}

/**
 * Implements hook_permission()
 *
 * This creates a section in the permissions admin area to allow permissions for this module.
 * @return array
 */
function imoneza_permission() {
  $iMoneza = \iMoneza\Drupal\App::getInstance();
  return $iMoneza->permissions();
}

/**
 * Implements hook_theme()
 *
 * @return array
 */
function imoneza_theme() {
  $iMoneza = \iMoneza\Drupal\App::getInstance();
  return $iMoneza->theme();
}

/**
 * Implements hook_help()
 * 
 * Displays help string for this module 
 * 
 * @param $path string
 * @param $arg mixed
 * @return null|string
 */
function imoneza_help($path, $arg) {
  $iMoneza = \iMoneza\Drupal\App::getInstance();
  return $iMoneza->help($path, $arg);
}

/**
 * Implements hook_forms()
 * 
 * Handles forms by the app
 * 
 * @param $formId
 * @param $args
 * @return array
 */
function imoneza_forms($formId, $args) {
  $iMoneza = \iMoneza\Drupal\App::getInstance();
  return [
    $formId =>  [
      'callback'  =>  array($iMoneza, 'form'),
      'callback arguments'  =>  array($formId)
    ]
  ];
}




/**
 * Implements the validation for first time form
 *
 * @param $form
 * @param $form_state
 */
function imoneza_first_time_form_validate($form, &$form_state) {
    $apiKey = $form_state['values']['manage_api_key'];
    $apiSecret = $form_state['values']['manage_api_secret'];

    form_set_error('manage_api_secret', 'this is a test error.');
}